# Generated by Django 3.0.4 on 2020-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('requested_at', models.DateField(auto_now=True)),
                ('email', models.CharField(max_length=50)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
