# Generated by Django 3.0.4 on 2020-05-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image',
            field=models.FileField(null=True, upload_to='image'),
        ),
    ]
