# Generated by Django 3.0.4 on 2020-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmodel_ordered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='image',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
