# Generated by Django 3.0.4 on 2020-05-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_ordermodel_owner'),
        ('projects', '0005_auto_20200512_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image2',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.OrderModel'),
        ),
    ]
