# Generated by Django 3.0.4 on 2020-05-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200512_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='image3',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
