# Generated by Django 3.0.6 on 2020-05-28 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_publicprojectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicprojectmodel',
            name='project_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_related_to', to='projects.ProjectModel'),
        ),
        migrations.AlterField(
            model_name='publicprojectmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
