# Generated by Django 3.0.6 on 2020-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200528_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
