# Generated by Django 3.0.6 on 2020-05-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectmodel_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='accepted',
            new_name='approved',
        ),
    ]
