# Generated by Django 3.0.6 on 2020-06-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200528_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChangesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('concept_number', models.DecimalField(decimal_places=1, max_digits=5)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_changes', to='projects.ProjectModel')),
            ],
        ),
    ]
