# Generated by Django 3.0.4 on 2020-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deadline_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('default_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('default_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('concept_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coloured_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
