# Generated by Django 3.0.4 on 2020-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='password_changed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
