# Generated by Django 3.0.4 on 2020-05-07 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=40)),
                ('address_line2', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('ordered_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='checkout.OrderModel')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Services')),
            ],
        ),
    ]
