# Generated by Django 3.0.4 on 2020-04-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=40)),
                ('address_line2', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('ordered_at', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
