# Generated by Django 3.0.4 on 2020-05-07 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('checkout', '0002_ordermodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.CreateModel(
            name='OrderLineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='checkout.OrderModel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.Services')),
            ],
        ),
    ]
