# Generated by Django 3.0.4 on 2020-05-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('checkout', '0003_auto_20200507_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlinemodel',
            name='owner',
        ),
        migrations.AlterField(
            model_name='orderlinemodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='checkout.OrderModel'),
        ),
        migrations.AlterField(
            model_name='orderlinemodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Services'),
        ),
    ]
